version: '3.9'

services:
    db:
        image: postgres
        ports:
            - ${DB_PORT}:5432
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD_FILE: run/secrets/db_password
        secrets:
            - db_password

secrets:
    db_password:
        file: ./secrets/db_password